### ISSUE TITLE
Visualization tool

### ISSUE THREAD

**Issue by gkeller2** [digs-uwo/dcsim#4]
@mtighe : should we upload it?

**Comment by mtighe** [comment]
I'm not sure... it's usefulness is pretty limited, and it's quite difficult to figure out how to use. Not because it's hard, but because it's not intuitive and buggy. I'm not sure it's worth fixing the couple of bugs that would be necessary to fix (for example, it doesn't save files to the correct location), and the code is quite badly structured.

**Comment by gkeller2** [comment]
Makes sense. I just thought I'd bring it up becuase I found the files laying around.

My thought was to upload it as a separate repository, but... yeah... let's leave it out for now...
